### ISSUE TITLE
Official docs

### ISSUE THREAD

**Issue by pra-dan** [ai-techsystems/arduino#1]
Hey @srohit0 Is there any official guide/documentation for understanding your work ? Also, I feel that examples would be great here.

**Comment by srohit0** [comment]
Documentation and examples are in compiler repo at bit.ly/dnnCompiler.

Will add example soon.

**Comment by srohit0** [comment]
Hello @PrashantDandriyal , please check out dir [examples](https://github.com/ai-techsystems/arduino/tree/master/examples) for first example using aits library.

Let's see what you can create with this.

**Comment by srohit0** [comment]
NN operator documents are found in the [deepC repository - click here](https://github.com/ai-techsystems/dnnCompiler/tree/master/include)
